# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LampAI',
                'doc_host': 'https://AndreRatzenberger.github.io',
                'git_url': 'https://github.com/AndreRatzenberger/LampAI',
                'lib_path': 'LampAI'},
  'syms': {'LampAI.core': {'LampAI.core.foo': ('core.html#foo', 'LampAI/core.py')}}}
